theme: jekyll-theme-midnight
title: Deep learning knowledge review
author: Gianluca Berardi
description: A place to review concepts about fundamental deep learing topics like linear algebra, statistics, machine learning and more !
